# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3889f417c5568f7c3afc30a5684f416125996027af6db93729b654031276b6eff930c3b17b4795d8fbed40e1c62e2b179e59ab0765713ed4edbd8ce663aafbf6

test:
  secret_key_base: 2ede54a7b31e90ed1bdf4e6ed5774289d9ebbef318332262826d3ed07f67f90cd1bc25d091e3d982d383a1771df97506cb0850e4ee40ec61b995dbc099fc9ad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
